//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.10 at 11:23:33 PM CEST 
//


package pakiecik;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the pakiecik package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Imieniny_QNAME = new QName("http://www.example.org/dane01", "Imieniny");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: pakiecik
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ImieninyType }
     * 
     */
    public ImieninyType createImieninyType() {
        return new ImieninyType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ImieninyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/dane01", name = "Imieniny")
    public JAXBElement<ImieninyType> createImieniny(ImieninyType value) {
        return new JAXBElement<ImieninyType>(_Imieniny_QNAME, ImieninyType.class, null, value);
    }

}
