/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Convolution */

#ifndef _Included_Convolution
#define _Included_Convolution
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Convolution
 * Method:    nativeConvolution
 * Signature: ([[I[[I)[[I
 */
JNIEXPORT jobjectArray JNICALL Java_Convolution_nativeConvolution
  (JNIEnv *, jobject, jobjectArray, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
